### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by yadiriaoliviamiguelaguilar** [SistemasTecTlaxiaco/actividad-2-infografia-yadiriaoliviamiguelaguilar#1]
[infografia.docx](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-yadiriaoliviamiguelaguilar/files/9465268/infografia.docx)
 
Yadiria Olivia Miguel Aguilar

**Comment by 11042002** [comment]
Tu calificación es de: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
